### ISSUE TITLE
feat: refactor contract into withContracts hook

### ISSUE THREAD

**Issue by mortimr** [ticket721/ethvtx#96]
## Description

Instead of storing classes that need both the store and the dispatch function, add a hook on top of the components to select contracts classes to create. Hook should give a `mapStateToProps` kinda func (allow taking an address/contract name from public props).

## Purpose

Currently, the store is stored statically into the class. We want to break this dependency (event emitter issues are occuring because of it)

## Who is going to work on it ?

- [x] I will do it
- [ ] I want to discuss this before I start working on it
- [ ] This is a feature request

**Comment by androolloyd** [comment]
any progress updates on this @mortimr ?

**Comment by mortimr** [comment]
Hi @androolloyd,

The feature is implemented [here](https://github.com/ticket721/ethvtx/tree/develop/react/sources/withContracts) and an example usage can be found [here](https://github.com/ticket721/ethvtx/tree/develop/examples/src/contract_showcase).

The feature is not yet published on npm, I just added a ticket for this week in order to finish this soon. 

I'll ping you when it's done
